name: pr-validate-wf
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
     branches:
       - develop

jobs:
    pr-validate-wf: 
      runs-on: ubuntu-latest
      steps:
        - name: Welcome Step 
          run: echo "Welcome to actions"
        - name: second step 
          run: echo "Actions"   
          


        
